# Generated by Django 2.0 on 2018-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxigram', '0009_auto_20181111_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.IntegerField(),
        ),
    ]
